dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/dashboard/dashboard-partnerships.html, dash/app-elements/dashboard/dashboard-personalized.html, dash/app-elements/data-table/data-table-header.html, dash/pages/page-dashboard.html, styles/list-styles.html
=> create dashboard HACT tab

dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/dashboard/dashboard-partnerships.html, dash/app-elements/dashboard/dashboard-personalized.html, dash/app-elements/data-table/data-table-header.html, dash/pages/page-dashboard.html, styles/list-styles.html
Implementation of the data-table and data api  for the hact- tab.
=> Hact data table

bower.json, dash/app-config/etools-app-config.html, dash/app-elements/dashboard/dashboard-data/partners-data.html, dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/dashboard/dashboard-personalized.html, dash/app-elements/data-table/data-table-column.html, dash/app-elements/data-table/data-table-header.html, dash/app-shell.html, dash/pages/page-dashboard.html, styles/hact-field-styles.html, styles/list-styles.html
HACT page laid out and routing setup for tabs. Added grouping feature to data table column.
=> HACT page and data table element additions

dash/app-config/etools-app-config.html, dash/app-elements/common-data-loaders.html, dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/dashboard/dashboard-personalized.html, dash/app-elements/static-common-data/actionPoints-byme-data.html, dash/app-elements/static-common-data/actionPoints-forme-data.html, dash/app-elements/static-common-data/redux-bahaviors/common-static-data-redux-bahavior.html, dash/app-elements/static-common-data/trips-data.html, dash/app-elements/static-common-data/trips-supervised-data.html, dash/app-shell.html, dash/pages/page-dashboard.html, package.json
=> Personalized-trips redux store

dash/app-config/etools-app-config.html, dash/app-elements/countries-data/countries-data.html, dash/app-elements/countries-dropdown/countries-dropdown.html, dash/app-elements/page-header/page-header.html, dash/app-shell.html
Countries dropdown now working
=> Countries dropdown fixed

dash/app-elements/dashboard/dashboard-data/trips-by-section-data.html, dash/app-elements/dashboard/dashboard-trips.html, dash/app-elements/static-common-data/redux-bahaviors/common-static-data-redux-bahavior.html, dash/app-elements/static-common-data/trips-months-data.html
Added dropdown to select year. This required additional functionality
to detect changes in each dropdown and highlight missing fields if any
and unhighlight invalid fields when clearing.
=> Trips tab year select added

dash/app-elements/dashboard/dashboard-trips.html, dash/pages/page-dashboard.html
Both charts now automatically resize based on number of bars.
Previously, labels would be hidden due to one-size-fits all config.
=> Charts styling / display bug fix

dash/app-elements/dashboard/dashboard-hact.html
HACT page now properly shows the table in IE
=> Flex box issues fixed for ie

bower.json, dash/app-behaviors/list-filters-behavior.html, dash/app-config/etools-app-config.html, dash/app-elements/dashboard/dashboard-data/map-interventions-data.html, dash/app-elements/dashboard/dashboard-data/map-locations-data.html, dash/app-elements/dashboard/dashboard-data/partners-data.html, dash/app-elements/dashboard/dashboard-data/partners-dropdown-data.html, dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/dashboard/dashboard-map.html, dash/app-elements/dashboard/dashboard-trips.html, dash/app-elements/marker-dialog/marker-dialog.html, dash/app-elements/static-common-data/actions.js, dash/app-elements/static-common-data/common-data-loaders.html, dash/app-elements/static-common-data/redux-bahaviors/common-static-data-redux-bahavior.html, dash/pages/page-dashboard.html, styles/list-styles.html, styles/shared-styles.html
Map and basic function added. Filtering still needs to be implemented on back end.
=> Maps Tab Added

bower.json, dash/app-elements/app-selector/app-selector.html, dash/app-elements/dashboard/dashboard-map.html, dash/app-elements/page-header/page-header.html, dash/app-elements/static-common-data/actions.js, styles/app-theme.html
App selector now comes from bower. Ability to customize by passing in
menu-options attribute.
=> App selector bower test

dash/app-elements/page-header/page-header.html, styles/app-theme.html
Profile icon in header toolbar now opens a dropdown with profile and
Sign out options
=> Profile dropdown

dash/app-config/etools-app-config.html, dash/app-elements/dashboard/dashboard-data/map-interventions-data.html, dash/app-elements/dashboard/dashboard-map.html, dash/app-elements/marker-dialog/marker-dialog.html, scripts/actions/actions.js, styles/shared-styles.html
Map loads to current country and zoomed in to appropriate level
=> Dashboard(MAP): map loads to current country and uses initial zoom

dash/app-elements/dashboard/dashboard-personalized.html, scripts/actions/actions.js, styles/list-styles.html
connects unicef/etools-issues#222
=> action pts description link

dash/app-config/etools-app-config.html, dash/app-elements/dashboard/dashboard-personalized.html, styles/list-styles.html
connects unicef/etools-issues#223
=> Change assigned by me and for assigned for me filtering on personalized tab

bower.json, dash/app-behaviors/common-general-behavior.html, dash/app-elements/dashboard/dashboard-personalized.html
connects unicef/etools-issues#220
=> Open links new window / ctrl click

Dockerfile, Dockerfile-dev
https://github.com/unicef/etools-issues/issues/592
=> add bash to docker container

dash/app-elements/dashboard/dashboard-personalized.html
connects unicef/etools-issues#222
=> fixed broken links on description, personalized tab

dash/app-elements/dashboard/dashboard-map.html
…loaded generic map by default
=> added console warning for countries without default map coordinates

dash/app-elements/dashboard/dashboard-data/partners-data.html, dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/data-table/data-table-column.html, dash/app-elements/data-table/data-table-row.html
connects unicef/etools-issues#534
=> Totals hact

dash/app-elements/dashboard/dashboard-data/partners-data.html, dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/data-table/data-table-footer.html
=> fixes dashboard hact totals

bower.json, dash/app-behaviors/common-general-behavior.html, dash/app-config/etools-app-config.html, dash/app-elements/dashboard/dashboard-personalized.html
connects unicef/etools-issues#223 , unicef/etools-issues#703
=> app selector update, action points statuses fixes and updates

dash/app-elements/dashboard/dashboard-personalized.html, scripts/actions/actions.js
connects unicef/etools-issues#783
=> Total unicef budget

dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/dashboard/dashboard-partnerships.html
connects unicef/etools-issues#713
=> Adds tooltip and changes tooltip position

dash/app-behaviors/common-general-behavior.html, dash/app-elements/dashboard/dashboard-partnerships.html
connects unicef/etools-issues#826
=> Fixes percentage display, default filtering on status

bower.json, dash/app-elements/dashboard/dashboard-partnerships.html
connects unicef/etools-issues#867
=> adds tooltip to dashboard-partnerships

dash/app-elements/dashboard/dashboard-partnerships.html
connects unicef/etools-issues#902
=> Hides tooltip on CSO dash

bower.json, dash/app-config/etools-app-config.html, dash/app-elements/dashboard/dashboard-data/partners-data.html, dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-charts.html, dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-detail.html, dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-general.html, dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/dashboard/dashboard-personalized.html, dash/app-elements/data-table/data-table-column.html, dash/app-elements/data-table/data-table-header.html, dash/pages/page-dashboard.html, styles/grid-layout-styles.html, styles/list-styles.html
Reverts unicef/etools-dashboard#207
=> Revert "Revert "Adds detailed assurance toggle; styling unfinished""

dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-general.html
just changed to the new endpoint
=> updates outstanding_findings endpoint

dash/app-elements/dashboard/dashboard-data/partners-data.html, dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-detail.html, dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-general.html
connects unicef/etools-issues#954
=> Hact updates

dash/app-elements/dashboard/dashboard-data/partners-data.html, dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-detail.html, dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-general.html, dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/data-table/data-table-header.html, dash/pages/page-dashboard.html, styles/hact-tables-styles.html
connects unicef/etools-issues#1133
=> Hact future quarterly

bower.json, dash/app-behaviors/data-element-behavior.html, dash/app-behaviors/list-filters-behavior.html, dash/app-behaviors/pagination-with-filters-behavior.html, dash/app-config/etools-app-config.html, dash/app-elements/dashboard/dashboard-attachments-lib.html, dash/app-elements/dashboard/dashboard-data/attachments-data.html, dash/app-elements/dashboard/dashboard-data/partners-data.html, dash/app-elements/dashboard/dashboard-data/partnership-data.html, dash/app-elements/dashboard/dashboard-hact.html, dash/app-elements/dashboard/dashboard-map.html, dash/app-elements/dashboard/dashboard-partnerships.html, dash/app-elements/dashboard/dashboard-personalized.html, dash/app-elements/static-common-data/common-data-loaders.html, dash/app-shell.html, dash/pages/page-dashboard.html, scripts/actions/actions.js, styles/grid-layout-styles.html, styles/list-styles.html
New tab for attachments. Implements new behavior for pagination on filtered lists.
=> Document Library

dash/app-config/etools-app-config.html, dash/app-elements/static-common-data/common-data-loaders.html, scripts/actions/actions.js
Fixing caching for redux assets
=> Caching fixes

dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-detail.html, dash/app-elements/dashboard/dashboard-hact-views/dashboard-hact-general.html, dash/app-elements/dashboard/dashboard-hact.html
https://app.clubhouse.io/unicefetools/story/4919/enhancement-to-hact-link-partner-name-to-partner-overview
=> Fixes IP Name links in hact on dash

dash/app-elements/dashboard/dashboard-partnerships.html
=> Add error message when currencies don't match for FCs

dash/app/components/data-table/data-table-footer.html, dash/app/views/partnerships/data/partnership-data.html, dash/app/views/partnerships/view-partnerships.html
=> Cso filter presets alt

bower.json
=> Updates piwik version in bower

dash/app/views/partnerships/data/partnership-data.html
=> Cso presets fix

dash/app/views/partnerships/view-partnerships.html
=> Cso dash update

dash/app-shell.html
=> Adds _goToAddTrips function to dash

dash/app/mixins/date-mixin.html, dash/app/views/partnerships/data/partnership-data.html
=> Fixes handling of date picker on CSO dash

dash/app/views/partnerships/view-partnerships.html
=> Updates tooltip for Actual Disbursement column CSO dash

dash/app/views/partnerships/data/partnership-data.html
=> Fixes expiring next 30 days filter on cso dash

dash/app/views/hact/elements/hact-charts.html
=> Updates colors for assurance coverage graphs

dash/app/views/hact/elements/hact-detail.html, dash/app/views/hact/elements/hact-edit-dialog.html, dash/app/views/hact/elements/hact-general.html
=> Updates hact dash data mapping and adds FU Spot Checks to edit dialog

dash/app-shell.html, dash/app/components/page-header.html, dash/app/config/config.html, dash/app/styles/app-theme.html
=> Changes nonproduction header color, adds staging notification text to dash

dash/app/views/hact/elements/hact-general.html
Gives hact assessment type ellipsis and adds tooltip
=> Hact styling fix

dash/app/styles/list-styles.html, dash/app/views/personalized/view-personalized.html
=> Adds headings to personalized dash sections

bower.json, dash/app/components/common-data-loaders.html
=> Updates to etools-app-selector v2.0.1

dash/app/mixins/date-mixin.html, dash/app/views/partnerships/view-partnerships.html
=> Switches function used to process date in CSO dash

bower.json
=> Updates etools-profile-dropdown component to remove fields

dash/app-shell.html, dash/app/views/personalized/view-personalized.html
=> Updates personalized dashboard page

dash/app/views/attachments/elements/attachments-grouped.html, dash/app/views/attachments/elements/sub-attachments.html
=> Adds tooltips, adds no results notification

dash/app/views/attachments/elements/attachments-grouped.html
=> Removes spread operator for IE compatibility

dash/app/views/personalized/view-personalized.html
=> Fixes Action Points No Results notification

dash/app/views/personalized/view-personalized.html
=> Fixes copy on personalized dashboard

dash/app/endpoints/endpoints.html
=> Updates endpoints for action points in personalized dash

dash/app/endpoints/endpoints.html
=> Adds ordering filter to personalized action points

dash/app/views/personalized/view-personalized.html
=> Removes default visible scrollbar in IE on personalized dash

dash/app/views/hact/elements/hact-edit-dialog.html
=> Makes display of editable Planned Prog. Visits conditional

bower.json, dash/app/mixins/list-filters-mixin.html, dash/app/styles/list-styles.html, dash/app/views/attachments/view-attachments.html, dash/app/views/map/view-map.html, dash/app/views/partnerships/view-partnerships.html, dash/app/views/trips/view-trips.html
=> Update filters behavior for CSO, Attachments, and Trips dashes

dash/app/views/attachments/elements/attachments-grouped.html, dash/app/views/attachments/view-attachments.html
=> Adds 'source' data from endpoint update

dash/app/config/dexie-db-config.html, dash/app/scripts/ramda-utils.html, dash/app/styles/partnerships-styles.html, dash/app/views/partnerships/data/partnership-dashboard-data.html, dash/app/views/partnerships/data/partnership-data.html, dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/partnerships/elements/partnerships-overview.html, dash/app/views/partnerships/view-partnerships.html
=> fixes split function for sections on cso-dash

dash/app/views/partnerships/data/partnership-dashboard-data.html
=> Fixes sectors filter on cso-dashboard

dash/app/views/partnerships/elements/cso-dashboard.html
=> Inserts currency format function and adds link to apd

dash/app/views/hact/elements/hact-charts.html
=>  Removes 'section under construction' warnings from hact dash charts

dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/partnerships/elements/partnerships-overview.html
=> Adds vendor number and adjusts columns in cso dashboard

dash/app/views/partnerships/elements/partnerships-overview.html
=> Updates handling of older PDSSFA numbers display in cso overview

bower.json, dash/app/views/partnerships/data/partnership-dashboard-data.html, dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/partnerships/view-partnerships.html
=> Partnership enhancement

dash/app/views/partnerships/data/partnership-dashboard-data.html, dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/partnerships/elements/partnerships-overview.html, dash/app/views/partnerships/view-partnerships.html
=> Ip dash export

dash/app/views/partnerships/data/partnership-dashboard-data.html, dash/app/views/partnerships/data/partnership-data.html, dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/partnerships/elements/partnerships-overview.html
=> Moves disabled alerts from cso overview to cso dashboard view

dash/app/views/partnerships/data/partnership-dashboard-data.html, dash/app/views/partnerships/elements/cso-dashboard.html
=> Updates alert filters with new flags from endpoint

dash/app/views/partnerships/elements/cso-dashboard.html
=> Hides 'Cost Centre' column on cso dashboard

dash/app/config/dexie-db-config.html, dash/app/endpoints/endpoints.html, dash/app/views/partnerships/data/partnership-data.html, dash/app/views/partnerships/data/partnership-overview-data.html, dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/partnerships/elements/partnerships-overview.html, dash/app/views/partnerships/view-partnerships.html
=> Switches partnerships views

dash/app/components/data-table/data-table-header.html, dash/app/views/partnerships/data/partnership-data.html, dash/app/views/partnerships/data/partnership-overview-data.html, dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/partnerships/elements/partnerships-overview.html
=> Ip dash fixes

dash/app/views/partnerships/elements/partnerships-overview.html
=> Updates apd link in partnerships dash to include status=open

dash/app/views/map/view-map.html
=> Fixes default filter for CP structure

dash/app/views/partnerships/data/partnership-data.html, dash/app/views/partnerships/data/partnership-overview-data.html, dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/personalized/view-personalized.html
=> Updates conidtions for showing flags on CSO dash and my dashboard

dash/app/views/trips/view-trips.html
=> Changes labels for aps by section and fixes calculation of open

dash/app/views/trips/view-trips.html
=> Removes 10% label and ticks for 'action points by section' graph

dash/app/endpoints/endpoints.html
=> Updates hact graphs endpoint to '/api/v2/hact/graph/2019'

dash/app/components/page-header.html
=> Changes logout link to /logout

dash/app/mixins/ajax-server-errors-mixin.html
=> Ensures a more detailed toast message appears if user not logged in

dash/app/components/common-data-loaders.html, dash/app/components/reduxProps.html, dash/app/mixins/redux-store-mixin.html, dash/app/views/personalized/view-personalized.html
=> Adds pdssfas to state, removes timeout function

dash/app/views/partnerships/elements/cso-dashboard.html, dash/app/views/partnerships/elements/partnerships-overview.html
=> Fixes error in partnership export url to remove an extra slash

dash/app-shell.html
=> Fixes routing error for attachments and maps

dash/app-shell.html, dash/app/views/hact/view-hact.html
=> Fixes export of two different hact views

dash/app/components/page-header.html, dash/app/config/config.html
=> Env notification

dash/app/components/page-header.html, dash/app/components/support-btn.html, index.html
=> [PROD] Support tool update

bower.json, dash/app/endpoints/endpoints.html
=> Updates changecountry endpoint

dash/app/views/partnerships/elements/cso-dashboard.html
=> Removes console.log from cso dash

bower.json
=> Updates etools-dropdown

dash/app/views/attachments/data/attachments-data.html, dash/app/views/attachments/elements/attachments-grouped.html
=> Fixes use of etools-dropdown in grouped attachments page

bower.json
=> Updates etools-profile-dialog to 3.1.1

bower.json, dash/app/components/page-header.html
=> Updates etools-app-selector to v2.1.10

dash/app/views/partnerships/elements/partnerships-overview.html
=> Adds flags column, logic for calculating days til CVA expiration, different flags

bower.json, dash/app/views/personalized/view-personalized.html
=> Upgrades etools-app-selector to v2.2.0

dash/app/views/attachments/elements/attachments-grouped.html, dash/app/views/attachments/elements/sub-attachments.html, dash/app/views/attachments/view-attachments.html
=> Applies formatting to dates as datetime field in attachments dashboard

dash/app-shell.html
=> Automates export links for hact detail/general/charts views

dash/app-shell.html
=> Fixes typo in export endpoint for hact

bower.json
=> Upgrades to app selector 2.2.2

src_ts/mixins/data-element-mixin.ts, src_ts/views/partnerships/data/partnership-data.ts, src_ts/views/partnerships/data/partnership-overview-data.ts
[ch24815] [Dash]Use old content for 'Partnerships' tab and migrate to Polymer 3
=> [ch24815] [Dash]Use old content for 'Partnerships' tab and migrate to Polymer 3

src_ts/views/view-partnerships.ts
[ch24815] [view-partnerships] Use old content for 'Partnerships' tab and migrate to Polymer 3
=> [ch24815] [view-partnerships] Use old content for 'Partnerships' tab and migrate to Polymer 3

src_ts/views/partnerships/elements/cso-dashboard.ts, src_ts/views/partnerships/elements/partnerships-overview.ts
[ch24815] [Dash]Use old content for 'Partnerships' tab and migrate to Polymer 3
=> [ch24815] [Dash]Use old content for 'Partnerships' tab and migrate to Polymer 3 

src_ts/components/data-table/data-table-column.ts
=> Dashboard build fix

src_ts/app-shell.ts, src_ts/views/partnerships/data/partnership-data.ts, src_ts/views/partnerships/elements/cso-dashboard.ts, src_ts/views/partnerships/elements/partnerships-overview.ts
[ch24815] [Fixes] Use old content for 'Partnerships' tab and migrate to Polymer 3
=> [ch24815] [Fixes] Use old content for 'Partnerships' tab and migrate to Polymer 3

src_ts/components/countries-dropdown.ts
[ch24815] [Fixes] Use old content for 'Partnerships' tab and migrate to Polymer 3
=> [ch24815] [Fixes] Use old content for 'Partnerships' tab and migrate to Polymer 3 

src_ts/app-shell.ts, src_ts/views/view-partnerships.ts
=> [ch25087]Reinstate Power BI Partnerships

src_ts/components/support-btn.ts
[ch26816] Update support link in header
=> [ch26816] Update support link in header

src_ts/pages/partnerships/elements/cso-dashboard.ts, src_ts/pages/view-partnerships.ts, src_ts/styles/partnerships-styles.ts
=> [ch27777]Fix content overflow and stacking on top one another

src_ts/endpoints/power-bi-embeds.ts
=> [ch26820]Don't show other tabs inside the FAM embed

src_ts/endpoints/power-bi-embeds.ts, src_ts/pages/view-personalized.ts
=> [ch28823]Update personalized embed

src_ts/pages/view-personalized.ts
=> [ch29077]Personalized embed for dev

src_ts/endpoints/power-bi-embeds.ts, src_ts/pages/view-personalized.ts
=> [ch28823]Personalized embed for prod & missing ampersand

src_ts/app-shell.ts
=> [ch27257]Remove Hact tab export links

src_ts/app-shell.ts
Reverts unicef/etools-dashboard#715
=> Revert "[ch27257]Remove Hact tab export links" - remove Exports , but restore Historical Exports

polymer.json, src_ts/app-shell.ts, src_ts/endpoints/power-bi-embeds.ts, src_ts/pages/view-fmm.ts, src_ts/pages/view-fmp.ts
[ch32648] Add new tab to dashboard for Field Monitoring
=> [ch32648] Add new tab to dashboard for Field Monitoring

src_ts/pages/view-fmm.ts, src_ts/pages/view-fmp.ts
=> Fix Powerbi links

.circleci/config.yml, express.js
=> [ch35206] Fix express error

src_ts/components/pages/view-fam.ts, src_ts/components/pages/view-fmm.ts, src_ts/components/pages/view-fmp.ts, src_ts/components/pages/view-partnerships.ts
[ch39148] Dashboards are showing blank
=> [ch39148] Dashboards are showing blank
